In [43]:
install.packages("factoextra", dependencies = TRUE)

also installing the dependencies ‘pixmap’, ‘ade4’, ‘ca’, ‘igraph’, ‘mclust’

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

In [39]:
library(tidyverse)
library(quantmod)
library(factoextra)

Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa

In [6]:
library(repr)
options(repr.plot.width=5, repr.plot.height=3)

K-means is based on unsupervised learning – you give the data and k-means decides how to classify it. The idea is to split data into clusters based on cluster center and assign each point to nearest center.  There is drawback with such approach – the algorithm tries to establish the centers of  clusters with initial data set. If the data is very noisy and the centers are not stable, then every try will give you different results.

\begin{equation}
W(C_k) = \sum\limits_{x_i \in C_k} (x_i - \mu_k)^2
\end{equation}


- xi design a data point belonging to the cluster Ck
- μk is the mean value of the points assigned to the cluster Ck


Each observation (xi) is assigned to a given cluster such that the sum of squares (SS) distance of the observation to their assigned cluster centers μk is a minimum.



We define the total within-cluster variation as follow:


\begin{equation}
tot.withinss = \sum\limits_{k=1}^k W(C_k) = \sum\limits_{k=1}^k \sum\limits_{x_i \in C_k} (x_i - \mu_k)^2
\end{equation}

Kmeans
 - Specify the number of clusters (K) to be created (by the analyst)
 - Select randomly k objects from the dataset as the initial cluster centers or means
 - Assigns each observation to their closest centroid, based on the Euclidean distance between the object and the centroid
 - For each of the k clusters update the cluster centroid by calculating the new mean values of all the data points in the cluster. The centoid of a Kth cluster is a vector of length p containing the means of all variables for the observations in the kth cluster; p is the number of variables.
 - Iteratively minimize the total within sum of square. That is, iterate steps 3 and 4 until the cluster assignments stop changing or the maximum number of iterations is reached. By default, the R software uses 10 as the default value for the maximum number of iterations.

In [45]:
data("iris")
df <- iris
head(df, 3)

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa
2 4.9          3.0         1.4          0.2         setosa
3 4.7          3.2         1.3          0.2         setosa

In [46]:
# Compute k-means with k = 3
set.seed(123)
res.km <- kmeans(scale(df[, -5]), 3, nstart = 25)
# K-means clusters showing the group of each individuals
res.km$cluster

  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [38] 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 3 2 2 2 3 2 2 2 2 2 2 2 2 3 2 2 2 2 3 2 2 2
 [75] 2 3 3 3 2 2 2 2 2 2 2 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 3 3 3 3 2 3 3 3 3
[112] 3 3 2 2 3 3 3 3 2 3 2 3 2 3 3 2 3 3 3 3 3 3 2 2 3 3 3 2 3 3 3 2 3 3 3 2 3
[149] 3 2

In [48]:
install.packages("remotes")

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

In [56]:
packageurl <- "https://cran.r-project.org/src/contrib/broom_0.7.3.tar.gz"
install.packages(packageurl, repos=NULL, type="source")

fviz_cluster(res.km, data = df[, -5],
             palette = c("#2E9FDF", "#00AFBB", "#E7B800"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )

In [28]:
data("USArrests")      # Loading the data set
df <- scale(USArrests) # Scaling the data

# View the firt 3 rows of the data
head(df, n = 3)

        Murder     Assault   UrbanPop   Rape
Alabama 1.24256408 0.7828393 -0.5209066 -0.003416473
Alaska  0.50786248 1.1068225 -1.2117642  2.484202941
Arizona 0.07163341 1.4788032  0.9989801  1.042878388

In [31]:
km.res <- kmeans(df, 4, nstart = 25)

In [32]:
print(km.res)

K-means clustering with 4 clusters of sizes 8, 16, 13, 13

Cluster means:
      Murder    Assault   UrbanPop        Rape
1  1.4118898  0.8743346 -0.8145211  0.01927104
2 -0.4894375 -0.3826001  0.5758298 -0.26165379
3  0.6950701  1.0394414  0.7226370  1.27693964
4 -0.9615407 -1.1066010 -0.9301069 -0.96676331

Clustering vector:
       Alabama         Alaska        Arizona       Arkansas     California
             1              3              3              1              3
      Colorado    Connecticut       Delaware        Florida        Georgia
             3              2              2              3              1
        Hawaii          Idaho       Illinois        Indiana           Iowa
             2              4              3              2              4
        Kansas       Kentucky      Louisiana          Maine       Maryland
             2              4              1              4              3
 Massachusetts       Michigan      Minnesota    Mississippi       Missouri
             2              3              4              1              3
       Montana       Nebraska         Nevada  New Hampshire     New Jersey
             4              4              3              4              2
    New Mexico       New York North Carolina   North Dakota           Ohio
             3              3              1              4              2
      Oklahoma         Oregon   Pennsylvania   Rhode Island South Carolina
             2              2              2              2              1
  South Dakota      Tennessee          Texas           Utah        Vermont
             4              1              3              2              4
      Virginia     Washington  West Virginia      Wisconsin        Wyoming
             2              2              4              4              2

Within cluster sum of squares by cluster:
[1]  8.316061 16.212213 19.922437 11.952463
 (between_SS / total_SS =  71.2 %)

Available components:

[1] "cluster"      "centers"      "totss"        "withinss"     "tot.withinss"
[6] "betweenss"    "size"         "iter"         "ifault"

In [33]:
dd <- cbind(USArrests, cluster = km.res$cluster)
head(dd)

           Murder Assault UrbanPop Rape cluster
Alabama    13.2   236     58       21.2 1
Alaska     10.0   263     48       44.5 3
Arizona     8.1   294     80       31.0 3
Arkansas    8.8   190     50       19.5 1
California  9.0   276     91       40.6 3
Colorado    7.9   204     78       38.7 3

In [35]:
km.res$centers

  Murder     Assault    UrbanPop   Rape
1  1.4118898  0.8743346 -0.8145211  0.01927104
2 -0.4894375 -0.3826001  0.5758298 -0.26165379
3  0.6950701  1.0394414  0.7226370  1.27693964
4 -0.9615407 -1.1066010 -0.9301069 -0.96676331

In [41]:
install.packages("broom")

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

# Show points only
fviz_cluster(km.res, iris[, -5], geom = "point")
# Show text only
fviz_cluster(km.res, iris[, -5], geom = "text")